"""empty message

Revision ID: 34361e035542
Revises: 
Create Date: 2023-11-20 21:35:39.328966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34361e035542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('order_items', sa.String(length=5000), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('bill_total', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('bill_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_table('book_table',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('bdate', sa.String(length=50), nullable=True),
    sa.Column('btime', sa.String(length=50), nullable=True),
    sa.Column('num_peoples', sa.Integer(), nullable=True),
    sa.Column('special', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('menu_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('pic', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=5), nullable=True),
    sa.Column('list_order', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('items_json', sa.String(length=5000), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('table', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('bill_clear', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('rating',
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('r_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('r_id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('role_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_users')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('rating')
    op.drop_table('order')
    op.drop_table('menu_item')
    op.drop_table('book_table')
    op.drop_table('bill')
    # ### end Alembic commands ###
