"""empty message

Revision ID: f348978cdd4d
Revises: 34361e035542
Create Date: 2023-11-20 21:48:34.093285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f348978cdd4d'
down_revision = '34361e035542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'list_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item', sa.Column('list_order', mysql.VARCHAR(length=55), nullable=True))
    # ### end Alembic commands ###
